project_name: posts

env_files:
  github_token: ${{ secrets.GITHUB_TOKEN }}

release:
  github:
    owner: go-animal-crossing
    name: posts

builds:
  - binary: posts
    id: posts
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64